org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true
org.gradle.caching=true

mod_id=ae2fct
mod_name=AE2 Fluid Crafting Terminal
mod_license=GNU LGPL 3.0
mod_group_id=me.myogoo
mod_authors=myogoo
mod_description=Adds fluid-aware recipe handling and crafting support to Applied Energistics 2 terminals.
